/* This file was generated by lv6 version master.737 (2727a7744111c84f7984634d2bd3ad6f7c6c7ff9). */
/*  lv6 -2cgc -node main convertible.lus */
/* on vanoise the 08/05/2019 at 23:54:11 */

#include <stdlib.h>
#include <stdio.h>
#include <unistd.h>
#include <stdint.h>
#include "convertible_main.h" 
#include "../clock.h"

/* MACROS DEFINITIONS ****************/
#ifndef TT
#define TT "1"
#endif
#ifndef FF
#define FF "0"
#endif
#ifndef BB
#define BB "bottom"
#endif
#ifdef CKCHECK
/* set this macro for testing output clocks */
#endif

static uint32_t dm_random_uint32(void) {
  static uint32_t current=UINT32_C(0xDEADBEEF);
  current = ((uint64_t) current << 6) % UINT32_C(4294967291);
  return current;
}

/* Standard Input procedures **************/
_boolean _get_bool(char* n){
  return dm_random_uint32() & 1;
}
/*
_integer _get_int(char* n){
  return (_integer) (dm_random_uint32() % 21) - 10;
}
*/
_real _get_real(char* n){
  return ((_integer) (dm_random_uint32() % 2000001) - 1000000)*1E-6;  
}
/* Output procedures **********************/
void convertible_main_O_n(void* cdata, _integer _V) {
}

/* Main procedure *************************/
int main(){
  int _s = 0;
  _boolean Start;
  _boolean Parked;
  _boolean Rot;
  _boolean Tick;
  _boolean OnOff;
  _boolean Done;
  _real Dist;
  _boolean Danger;
  _boolean Locked;
  _real Speed;
  _real Roof_Speed;
  convertible_main_ctx_type ctx_struct;
  convertible_main_ctx_type* ctx = &ctx_struct;
  convertible_main_ctx_init(ctx);
  // printf("#inputs \"Start\":bool \"Parked\":bool \"Rot\":bool \"Tick\":bool \"OnOff\":bool \"Done\":bool \"Dist\":real\n");
  // printf("#outputs \"Danger\":bool \"Locked\":bool \"Speed\":real \"Roof_Speed\":real\n");

  /* Main loop */
  clock_prepare();
  clock_start();
  
  for(int count=0; count<1000; count++){
    ++_s;
     Start = _get_bool("Start");
     Parked = _get_bool("Parked");
     Rot = _get_bool("Rot");
     Tick = _get_bool("Tick");
     OnOff = _get_bool("OnOff");
     Done = _get_bool("Done");
     Dist = _get_real("Dist");
    convertible_main_step(Start,Parked,Rot,Tick,OnOff,Done,Dist,&Danger,&Locked,&Speed,&Roof_Speed,ctx);
    // printf("%d %d %d %d %d %d %f #outs %d %d %f %f\n",Start,Parked,Rot,Tick,OnOff,Done,Dist,Danger,Locked,Speed,Roof_Speed);
    // printf("%d %d %f %f\n",Danger,Locked,Speed,Roof_Speed);
  }

  clock_stop();
  print_total_clock();
  
  return 0;
   
}
