/* This file was generated by lv6 version master.737 (2727a7744111c84f7984634d2bd3ad6f7c6c7ff9). */
/*  lv6 -2cgc -node main convertible.lus */
/* on vanoise the 08/05/2019 at 23:54:11 */

#include <stdlib.h>
#include <string.h>

#include "lustre_types.h"
#include "lustre_consts.h"

#ifndef _convertible_main_H_FILE
#define _convertible_main_H_FILE
void Lustre_arrow_ctx_reset(Lustre_arrow_ctx_type* ctx);
void Lustre_arrow_ctx_init(Lustre_arrow_ctx_type* ctx);
void Lustre_arrow_step(_integer ,_integer ,_integer *,Lustre_arrow_ctx_type*);

void Lustre_arrow_2_ctx_reset(Lustre_arrow_2_ctx_type* ctx);
void Lustre_arrow_2_ctx_init(Lustre_arrow_2_ctx_type* ctx);
void Lustre_arrow_2_step(_real ,_real ,_real *,Lustre_arrow_2_ctx_type*);

void Lustre_arrow_3_ctx_reset(Lustre_arrow_3_ctx_type* ctx);
void Lustre_arrow_3_ctx_init(Lustre_arrow_3_ctx_type* ctx);
void Lustre_arrow_3_step(_real [50],_real [50],_real [50]/*out*/,Lustre_arrow_3_ctx_type*);

void Lustre_hat_step(_real ,_real [50]/*out*/);

void Lustre_pre_ctx_reset(Lustre_pre_ctx_type* ctx);
void Lustre_pre_ctx_init(Lustre_pre_ctx_type* ctx);
void Lustre_pre_get(_integer *,Lustre_pre_ctx_type*);

void Lustre_pre_set(_integer ,Lustre_pre_ctx_type*);

void Lustre_pre_2_ctx_reset(Lustre_pre_2_ctx_type* ctx);
void Lustre_pre_2_ctx_init(Lustre_pre_2_ctx_type* ctx);
void Lustre_pre_2_get(_real *,Lustre_pre_2_ctx_type*);

void Lustre_pre_2_set(_real ,Lustre_pre_2_ctx_type*);

void Lustre_pre_3_ctx_reset(Lustre_pre_3_ctx_type* ctx);
void Lustre_pre_3_ctx_init(Lustre_pre_3_ctx_type* ctx);
void Lustre_pre_3_get(_real [50]/*out*/,Lustre_pre_3_ctx_type*);

void Lustre_pre_3_set(_real [50],Lustre_pre_3_ctx_type*);

void Lustre_slash_step(_real ,_real ,_real *);

void assign_50_step(_real ,_integer ,_real [50],_real [50]/*out*/);

void convertible_abs_step(_real ,_real *);

void convertible_braking_time_step(_real ,_real *);

void convertible_main_ctx_reset(convertible_main_ctx_type* ctx);
void convertible_main_ctx_init(convertible_main_ctx_type* ctx);
void convertible_main_step(_boolean ,_boolean ,_boolean ,_boolean ,_boolean ,_boolean ,_real ,_boolean *,_boolean *,_real *,_real *,convertible_main_ctx_type*);

void convertible_maxr_step(_real ,_real ,_real *);

void convertible_may_collide_ctx_reset(convertible_may_collide_ctx_type* ctx);
void convertible_may_collide_ctx_init(convertible_may_collide_ctx_type* ctx);
void convertible_may_collide_step(_real ,_real ,_boolean *,convertible_may_collide_ctx_type*);

void convertible_ms_to_kmh_step(_real ,_real *);

void convertible_roof_ctx_reset(convertible_roof_ctx_type* ctx);
void convertible_roof_ctx_init(convertible_roof_ctx_type* ctx);
void convertible_roof_step(_boolean ,_boolean ,_boolean ,_boolean ,_boolean *,_real *,convertible_roof_ctx_type*);

void convertible_roof_speed_ctx_reset(convertible_roof_speed_ctx_type* ctx);
void convertible_roof_speed_ctx_init(convertible_roof_speed_ctx_type* ctx);
void convertible_roof_speed_step(_boolean ,_real *,convertible_roof_speed_ctx_type*);

void convertible_solve_eq_d2_step(_real ,_real ,_real ,_real *);

void convertible_speed_kmh_ctx_reset(convertible_speed_kmh_ctx_type* ctx);
void convertible_speed_kmh_ctx_init(convertible_speed_kmh_ctx_type* ctx);
void convertible_speed_kmh_step(_boolean ,_boolean ,_real *,convertible_speed_kmh_ctx_type*);

void convertible_sqrt_step(_real ,_real *);

void convertible_vehicle_ctx_reset(convertible_vehicle_ctx_type* ctx);
void convertible_vehicle_ctx_init(convertible_vehicle_ctx_type* ctx);
void convertible_vehicle_step(_boolean ,_boolean ,_real ,_real ,_integer *,convertible_vehicle_ctx_type*);

void fillred_update_cell_do_50_step(convertible_update_acc ,_real [50],convertible_update_acc *,_real [50]/*out*/);

void red_rplus_50_real_step(_real ,_real [50],_real *);

void squareR_1_step(_real ,_real ,_real *);

void squareR_2_step(_real ,_real ,_real *);

void squareR_3_step(_real ,_real ,_real *);

void squareR_4_step(_real ,_real ,_real *);

void squareR_5_step(_real ,_real ,_real *);

void sum_50_0d0_ctx_reset(sum_50_0d0_ctx_type* ctx);
void sum_50_0d0_ctx_init(sum_50_0d0_ctx_type* ctx);
void sum_50_0d0_step(_real ,_real *,sum_50_0d0_ctx_type*);

void sum_50_0d1_ctx_reset(sum_50_0d1_ctx_type* ctx);
void sum_50_0d1_ctx_init(sum_50_0d1_ctx_type* ctx);
void sum_50_0d1_step(_real ,_real *,sum_50_0d1_ctx_type*);

void update_cell_do_50_step(convertible_update_acc ,_real ,convertible_update_acc *,_real *);

/////////////////////////////////////////////////
#endif
