/* This file was generated by lv6 version master.737 (2727a7744111c84f7984634d2bd3ad6f7c6c7ff9). */
/*  lv6 -2cgc -node main convertible.lus */
/* on vanoise the 08/05/2019 at 23:54:11 */

#ifndef _SOC2C_PREDEF_TYPES
#define _SOC2C_PREDEF_TYPES
typedef int _boolean;
typedef int _integer;
typedef char* _string;
typedef double _real;
typedef double _double;
typedef float _float;
#define _false 0
#define _true 1
#endif
// end of _SOC2C_PREDEF_TYPES
// User typedef 
#ifndef _convertible_main_TYPES
#define _convertible_main_TYPES
typedef _integer convertible_eq_case;
typedef _integer convertible_roof_speed_state;
typedef _integer convertible_roof_state;
typedef struct { 
   _integer i;
   _integer j;
   _real v;
  } convertible_update_acc;
typedef _integer convertible_vehicle_state;
#endif // enf of  _convertible_main_TYPES
// Memoryless soc ctx typedef 
// Memoryfull soc ctx typedef 
/* Lustre_pre_ctx */
typedef struct {
   /*Memory cell*/
   _integer _memory ;
} Lustre_pre_ctx_type;

/* Lustre_arrow_ctx */
typedef struct {
   /*Memory cell*/
   _boolean _memory ;
} Lustre_arrow_ctx_type;

/* Lustre_pre_2_ctx */
typedef struct {
   /*Memory cell*/
   _real _memory ;
} Lustre_pre_2_ctx_type;

/* Lustre_arrow_2_ctx */
typedef struct {
   /*Memory cell*/
   _boolean _memory ;
} Lustre_arrow_2_ctx_type;

/* convertible_roof_speed_ctx */
typedef struct {
   /*INSTANCES*/
   Lustre_pre_2_ctx_type Lustre_pre_2_ctx_tab[2];
   Lustre_pre_ctx_type Lustre_pre_ctx_tab[1];
   Lustre_arrow_2_ctx_type Lustre_arrow_2_ctx_tab[2];
   Lustre_arrow_ctx_type Lustre_arrow_ctx_tab[1];
} convertible_roof_speed_ctx_type;

/* convertible_roof_ctx */
typedef struct {
   /*INSTANCES*/
   convertible_roof_speed_ctx_type convertible_roof_speed_ctx_tab[1];
   Lustre_pre_ctx_type Lustre_pre_ctx_tab[1];
   Lustre_arrow_ctx_type Lustre_arrow_ctx_tab[1];
} convertible_roof_ctx_type;

/* Lustre_pre_3_ctx */
typedef struct {
   /*Memory cell*/
   _real _memory[50] ;
} Lustre_pre_3_ctx_type;

/* Lustre_arrow_3_ctx */
typedef struct {
   /*Memory cell*/
   _boolean _memory ;
} Lustre_arrow_3_ctx_type;

/* sum_50_0d0_ctx */
typedef struct {
   /*INSTANCES*/
   Lustre_pre_3_ctx_type Lustre_pre_3_ctx_tab[1];
   Lustre_pre_ctx_type Lustre_pre_ctx_tab[1];
   Lustre_arrow_3_ctx_type Lustre_arrow_3_ctx_tab[1];
   Lustre_arrow_ctx_type Lustre_arrow_ctx_tab[1];
} sum_50_0d0_ctx_type;

/* sum_50_0d1_ctx */
typedef struct {
   /*INSTANCES*/
   Lustre_pre_3_ctx_type Lustre_pre_3_ctx_tab[1];
   Lustre_pre_ctx_type Lustre_pre_ctx_tab[1];
   Lustre_arrow_3_ctx_type Lustre_arrow_3_ctx_tab[1];
   Lustre_arrow_ctx_type Lustre_arrow_ctx_tab[1];
} sum_50_0d1_ctx_type;

/* convertible_speed_kmh_ctx */
typedef struct {
   /*INSTANCES*/
   sum_50_0d1_ctx_type sum_50_0d1_ctx_tab[1];
   sum_50_0d0_ctx_type sum_50_0d0_ctx_tab[1];
   Lustre_pre_2_ctx_type Lustre_pre_2_ctx_tab[3];
   Lustre_arrow_2_ctx_type Lustre_arrow_2_ctx_tab[3];
} convertible_speed_kmh_ctx_type;

/* convertible_vehicle_ctx */
typedef struct {
   /*INSTANCES*/
   Lustre_pre_ctx_type Lustre_pre_ctx_tab[1];
   Lustre_arrow_ctx_type Lustre_arrow_ctx_tab[1];
} convertible_vehicle_ctx_type;

/* convertible_may_collide_ctx */
typedef struct {
   /*INSTANCES*/
   Lustre_pre_2_ctx_type Lustre_pre_2_ctx_tab[1];
   Lustre_arrow_2_ctx_type Lustre_arrow_2_ctx_tab[1];
} convertible_may_collide_ctx_type;

/* convertible_main_ctx */
typedef struct {
   /*INSTANCES*/
   convertible_vehicle_ctx_type convertible_vehicle_ctx_tab[1];
   convertible_speed_kmh_ctx_type convertible_speed_kmh_ctx_tab[1];
   convertible_roof_ctx_type convertible_roof_ctx_tab[1];
   convertible_may_collide_ctx_type convertible_may_collide_ctx_tab[1];
} convertible_main_ctx_type;

// Defining array and extern types assignments 

#ifndef _assign_rp50 
#define _assign_rp50(dest, source, size) memcpy(dest, source, size)
#endif
