# File generated by CompCert 3.4
# Command line: -S latency.c
	.text
	.balign 2
	.globl latency
latency:
	make    $r2 = 100
;;
	loopdo  $r2, .exitloop
;;
	lws	$r1 = 0[$r0]
;;
	addw	$r0 = $r0, 0
;; 
	addw	$r0 = $r0, 0
;; 
	addw	$r0 = $r0, 0
;; 
	addw	$r1 = $r1, 1
;;
	sw	0[$r0] = $r1
;;
.exitloop:	
	ret	
;;
	.type	latency, @function
	.size	latency, . - latency
