/* This file was generated by lv6 version master.737 (2727a7744111c84f7984634d2bd3ad6f7c6c7ff9). */
/*  lv6 -2c -en -2cgc -n main convertible.lus */
/* on vanoise the 09/05/2019 at 15:28:26 */

#include <stdlib.h>
#include <string.h>

#include "lustre_types.h"
#include "lustre_consts.h"

#ifndef _convertible_main_H_FILE
#define _convertible_main_H_FILE
void Lustre_arrow_2_ctx_reset(Lustre_arrow_2_ctx_type* ctx);
void Lustre_arrow_2_ctx_init(Lustre_arrow_2_ctx_type* ctx);
void Lustre_arrow_2_step(_integer ,_integer ,_integer *,Lustre_arrow_2_ctx_type*);

void Lustre_arrow_ctx_reset(Lustre_arrow_ctx_type* ctx);
void Lustre_arrow_ctx_init(Lustre_arrow_ctx_type* ctx);
void Lustre_arrow_step(_real ,_real ,_real *,Lustre_arrow_ctx_type*);

void Lustre_arrow_3_ctx_reset(Lustre_arrow_3_ctx_type* ctx);
void Lustre_arrow_3_ctx_init(Lustre_arrow_3_ctx_type* ctx);
void Lustre_arrow_3_step(_real [50],_real [50],_real [50]/*out*/,Lustre_arrow_3_ctx_type*);

void Lustre_hat_step(_real ,_real [50]/*out*/);

void Lustre_pre_2_ctx_reset(Lustre_pre_2_ctx_type* ctx);
void Lustre_pre_2_ctx_init(Lustre_pre_2_ctx_type* ctx);
void Lustre_pre_2_get(_integer *,Lustre_pre_2_ctx_type*);

void Lustre_pre_2_set(_integer ,Lustre_pre_2_ctx_type*);

void Lustre_pre_ctx_reset(Lustre_pre_ctx_type* ctx);
void Lustre_pre_ctx_init(Lustre_pre_ctx_type* ctx);
void Lustre_pre_get(_real *,Lustre_pre_ctx_type*);

void Lustre_pre_set(_real ,Lustre_pre_ctx_type*);

void Lustre_pre_3_ctx_reset(Lustre_pre_3_ctx_type* ctx);
void Lustre_pre_3_ctx_init(Lustre_pre_3_ctx_type* ctx);
void Lustre_pre_3_get(_real [50]/*out*/,Lustre_pre_3_ctx_type*);

void Lustre_pre_3_set(_real [50],Lustre_pre_3_ctx_type*);

void Lustre_slash_step(_real ,_real ,_real *);

void convertible_main_ctx_reset(convertible_main_ctx_type* ctx);
void convertible_main_ctx_init(convertible_main_ctx_type* ctx);
void convertible_main_step(_boolean ,_boolean ,_boolean ,_boolean ,_boolean ,_boolean ,_real ,_boolean *,_boolean *,_real *,_real *,convertible_main_ctx_type*);

/////////////////////////////////////////////////
#endif
