/* This file was generated by lv6 version master.737 (2727a7744111c84f7984634d2bd3ad6f7c6c7ff9). */
/*  lv6 -2c -en -2cgc -n main convertible.lus */
/* on vanoise the 09/05/2019 at 15:28:26 */
#include "lustre_consts.h"