/* This file was generated by lv6 version master.737 (2727a7744111c84f7984634d2bd3ad6f7c6c7ff9). */
/*  lv6 -2c -en -2cgc -n main convertible.lus */
/* on vanoise the 09/05/2019 at 15:28:26 */

// Constant definitions 
#define convertible_anti_col 2
#define convertible_deg1 1
#define convertible_fast 1
#define convertible_in_motion 1
#define convertible_k 5500.0
#define convertible_locked 0
#define convertible_max_roof_speed 10.0
#define convertible_no_sol 0
#define convertible_one_sol 2
#define convertible_period 0.1
#define convertible_run 1
#define convertible_size 50
#define convertible_slow 2
#define convertible_speed_max 110.0
#define convertible_stationnary 0
#define convertible_two_sol 3
#define convertible_wait 0
#define convertible_wheel_girth 1.4
