/* This file was generated by lv6 version master.737 (2727a7744111c84f7984634d2bd3ad6f7c6c7ff9). */
/*  lv6 carlightV2.lus -n carlight --to-c */
/* on vanoise the 08/05/2019 at 22:54:09 */

// Constant definitions 
#define carlightV2_AUTO 2
#define carlightV2_OFF 1
#define carlightV2_ON 0
#define carlightV2_period 0.5
