# -*- mode: makefile; -*-

CFILES=main.c solver.c clock.c
GCDAFILES=$(CFILES:.c=.gcda)
CCOMP=../../../ccomp
GCC=aarch64-linux-gnu-gcc  # k1-cos-gcc
LIBS=-lm
PROFILING_DAT=compcert_profiling.dat
EXECUTE=qemu-aarch64 # k1-cluster --
EXECUTE_CYCLES=k1-cluster --cycle-based --
EXAMPLE=sudoku.sat
CCOMPFLAGS=-finline-auto-threshold 50 -static -finline-asm
GCCFLAGS=-static
ALL=minisat.ccomp.log minisat.ccomp.trace-linearize.log minisat.ccomp.profiled.log minisat.gcc-O3.log minisat.gcc-O3.profiled.log

all: $(ALL)
exe: $(ALL:.log=.exe)

minisat.ccomp.exe: $(CFILES)
	$(CCOMP) $(CCOMPFLAGS) $(CFILES) -o $@ $(LIBS)

minisat.ccomp.profile-arcs.exe: $(CFILES)
	$(CCOMP) -DARM_NO_PRIVILEGE $(CCOMPFLAGS) -fprofile-arcs $(CFILES) -o $@ $(LIBS)

minisat.gcc-O3.exe: $(CFILES)
	$(GCC) $(GCCFLAGS) -O3 $(CFILES) -o $@ $(LIBS)

minisat.gcc-O3.profile-arcs.exe: $(CFILES)
	$(GCC) -DARM_NO_PRIVILEGE $(GCCFLAGS) -fprofile-arcs -O3 $(CFILES) -o $@ $(LIBS)

gcda: minisat.gcc-O3.profile-arcs.exe
	$(EXECUTE) $< $(EXAMPLE)

$(GCDAFILES): gcda

minisat.gcc-O3.profiled.exe: $(CFILES) $(GCDAFILES)
	$(GCC) $(GCCFLAGS) -O3 -fprofile-use $(CFILES) -o $@ $(LIBS)

minisat.ccomp.trace-linearize.exe: $(CFILES)
	$(CCOMP) $(CCOMPFLAGS) -ftracelinearize $(CFILES) -o $@ $(LIBS)

$(PROFILING_DAT): minisat.ccomp.profile-arcs.exe
	-rm -f $(PROFILING_DAT)
	$(EXECUTE) $< $(EXAMPLE)

minisat.ccomp.profiled.exe: $(CFILES) $(PROFILING_DAT)
	$(CCOMP) $(CCOMPFLAGS) -fprofile-use= $(PROFILING_DAT) -ftracelinearize $(CFILES) -o $@ $(LIBS)

%.log : %.exe
	$(EXECUTE_CYCLES) $< $(EXAMPLE) 2>&1 | tee $@

clean:
	-rm -f *.log *.exe $(PROFILING_DAT) $(GCDAFILES)

.PHONY: clean gcda exe all

.SECONDARY:
