/* This file was generated by lv6 version master.737 (2727a7744111c84f7984634d2bd3ad6f7c6c7ff9). */
/*  lv6 -en -2cgc heater_control.lus -n heater_control */
/* on vanoise the 15/05/2019 at 13:20:10 */

#include <stdlib.h>
#include <string.h>

#include "lustre_types.h"
#include "lustre_consts.h"

#ifndef _heater_control_heater_control_H_FILE
#define _heater_control_heater_control_H_FILE
void Lustre_arrow_ctx_reset(Lustre_arrow_ctx_type* ctx);
void Lustre_arrow_ctx_init(Lustre_arrow_ctx_type* ctx);
void Lustre_arrow_step(_boolean ,_boolean ,_boolean *,Lustre_arrow_ctx_type*);

void Lustre_pre_ctx_reset(Lustre_pre_ctx_type* ctx);
void Lustre_pre_ctx_init(Lustre_pre_ctx_type* ctx);
void Lustre_pre_get(_boolean *,Lustre_pre_ctx_type*);

void Lustre_pre_set(_boolean ,Lustre_pre_ctx_type*);

void Lustre_slash_step(_real ,_real ,_real *);

void heater_control_heater_control_ctx_reset(heater_control_heater_control_ctx_type* ctx);
void heater_control_heater_control_ctx_init(heater_control_heater_control_ctx_type* ctx);
void heater_control_heater_control_step(_real ,_real ,_real ,_real ,_boolean *,heater_control_heater_control_ctx_type*);

/////////////////////////////////////////////////
#endif
