/* This file was generated by lv6 version master.737 (2727a7744111c84f7984634d2bd3ad6f7c6c7ff9). */
/*  lv6 -en -2cgc heater_control.lus -n heater_control */
/* on vanoise the 15/05/2019 at 13:20:10 */

#ifndef _SOC2C_PREDEF_TYPES
#define _SOC2C_PREDEF_TYPES
typedef int _boolean;
typedef int _integer;
typedef char* _string;
typedef double _real;
typedef double _double;
typedef float _float;
#define _false 0
#define _true 1
#endif
// end of _SOC2C_PREDEF_TYPES
// User typedef 
#ifndef _heater_control_heater_control_TYPES
#define _heater_control_heater_control_TYPES
#endif // enf of  _heater_control_heater_control_TYPES
// Memoryless soc ctx typedef 
// Memoryfull soc ctx typedef 
/* Lustre_arrow_ctx */
typedef struct {
   /*Memory cell*/
   _boolean _memory ;
} Lustre_arrow_ctx_type;

/* Lustre_pre_ctx */
typedef struct {
   /*Memory cell*/
   _boolean _memory ;
} Lustre_pre_ctx_type;

/* heater_control_heater_control_ctx */
typedef struct {
   /*INSTANCES*/
   Lustre_pre_ctx_type Lustre_pre_ctx_tab[1];
   Lustre_arrow_ctx_type Lustre_arrow_ctx_tab[1];
} heater_control_heater_control_ctx_type;

