/* This file was generated by lv6 version master.737 (2727a7744111c84f7984634d2bd3ad6f7c6c7ff9). */
/*  lv6 -en -2cgc heater_control.lus -n heater_control */
/* on vanoise the 15/05/2019 at 13:20:10 */
#include "lustre_consts.h"