/* This file was generated by lv6 version master.737 (2727a7744111c84f7984634d2bd3ad6f7c6c7ff9). */
/*  lv6 -en -2cgc heater_control.lus -n heater_control */
/* on vanoise the 15/05/2019 at 13:20:10 */

// Constant definitions 
#define heater_control_DELTA 0.5
#define heater_control_FAILURE -999.0
#define heater_control_TMAX 9.0
#define heater_control_TMIN 6.0
