/* This file was generated by lv6 version master.737 (2727a7744111c84f7984634d2bd3ad6f7c6c7ff9). */
/*  lv6 carlightV2.lus -n carlight --to-c */
/* on vanoise the 08/05/2019 at 22:54:09 */

#include <stdlib.h>
#include <string.h>

#include "lustre_types.h"
#include "lustre_consts.h"

#ifndef _carlightV2_carlight_H_FILE
#define _carlightV2_carlight_H_FILE
void Lustre_arrow_ctx_reset(Lustre_arrow_ctx_type* ctx);
Lustre_arrow_ctx_type* Lustre_arrow_ctx_new_ctx();
void Lustre_arrow_step(_boolean ,_boolean ,_boolean *,Lustre_arrow_ctx_type*);

void Lustre_arrow_2_ctx_reset(Lustre_arrow_2_ctx_type* ctx);
Lustre_arrow_2_ctx_type* Lustre_arrow_2_ctx_new_ctx();
void Lustre_arrow_2_step(_real ,_real ,_real *,Lustre_arrow_2_ctx_type*);

void Lustre_pre_ctx_reset(Lustre_pre_ctx_type* ctx);
Lustre_pre_ctx_type* Lustre_pre_ctx_new_ctx();
void Lustre_pre_get(_boolean *,Lustre_pre_ctx_type*);

void Lustre_pre_set(_boolean ,Lustre_pre_ctx_type*);

void Lustre_pre_2_ctx_reset(Lustre_pre_2_ctx_type* ctx);
Lustre_pre_2_ctx_type* Lustre_pre_2_ctx_new_ctx();
void Lustre_pre_2_get(_real *,Lustre_pre_2_ctx_type*);

void Lustre_pre_2_set(_real ,Lustre_pre_2_ctx_type*);

void carlightV2_carlight_ctx_reset(carlightV2_carlight_ctx_type* ctx);
carlightV2_carlight_ctx_type* carlightV2_carlight_ctx_new_ctx();
void carlightV2_carlight_step(_integer ,_real ,_boolean *,carlightV2_carlight_ctx_type*);

void carlightV2_carlight_auto_ctx_reset(carlightV2_carlight_auto_ctx_type* ctx);
carlightV2_carlight_auto_ctx_type* carlightV2_carlight_auto_ctx_new_ctx();
void carlightV2_carlight_auto_step(_real ,_boolean ,_boolean *,carlightV2_carlight_auto_ctx_type*);

void carlightV2_front_montant_ctx_reset(carlightV2_front_montant_ctx_type* ctx);
carlightV2_front_montant_ctx_type* carlightV2_front_montant_ctx_new_ctx();
void carlightV2_front_montant_step(_boolean ,_boolean *,carlightV2_front_montant_ctx_type*);

void carlightV2_max_step(_real ,_real ,_real *);

void carlightV2_vrai_depuis_n_secondes_ctx_reset(carlightV2_vrai_depuis_n_secondes_ctx_type* ctx);
carlightV2_vrai_depuis_n_secondes_ctx_type* carlightV2_vrai_depuis_n_secondes_ctx_new_ctx();
void carlightV2_vrai_depuis_n_secondes_step(_boolean ,_real ,_boolean *,carlightV2_vrai_depuis_n_secondes_ctx_type*);

/////////////////////////////////////////////////
#endif
